#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

# Determine if setup is needed
if [ ! -f /usr/bin/apt ]; then
    echo "**** Image is not Ubuntu, exiting emby-mediainfo-plugin install. ****"
    exit 0
fi

if [ $(uname -m) != "x86_64" ]; then
    echo "**** MediaInfo plugin only works on x86_64, see README for more info.  Exiting emby-mediainfo-plugin install. ****"
    exit 0
fi

# Ubuntu
if [ -f /usr/bin/apt ]; then

    if [ $MKV_NEWER_VERSION == "TRUE" ]; then
        echo "Add newest version of MKVToolNix to package list."
        PACKAGES = "mkvtoolnix mkvtoolnix-gui"
    else  
        // Check to see if mkvpropedit is installed or if mkvpropedit installed and check to see if version 70.0 is installed.
        if [ ! -f /usr/bin/mkvpropedit ] || [( -f /usr/bin/mkvpropedit ) && ( mkvpropedit --version | grep -qPo "[\d]+.[\d]+" != "70.0" )]; then
            echo "**** Add version 70.0 of MKVToolNIX to package list. ****"

            # Check for MKVToolNix repository
            if [ ! -f /etc/apt/sources.list.d/mkvtoolnix.download.list ] ; then
	            # Import MKVToolNix GPG key 
	            curl -o /usr/share/keyrings/gpg-pub-moritzbunkus.gpg https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg

	            # Add MKVToolNix repository
	            echo "\
                deb [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ jammy main \
                deb-src [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ jammy main" \
                >> /etc/apt/sources.list.d/mkvtoolnix.download.list
            fi

            if ! grep -E -q 'deb\s+http://archive\.ubuntu\.com/ubuntu/ +jammy.*main' /etc/apt/sources.list /etc/apt/sources.list.d/*; then
                echo "deb http://archive.ubuntu.com/ubuntu/ jammy main" >> /etc/apt/sources.list
            fi
            if ! grep -E -q 'deb\s+http://archive\.ubuntu\.com/ubuntu/ +jammy.*universe' /etc/apt/sources.list /etc/apt/sources.list.d/*; then
                echo "deb http://archive.ubuntu.com/ubuntu/ jammy universe" >> /etc/apt/sources.list
            fi
            if ! grep -E -q 'deb-src\s+http://archive\.ubuntu\.com/ubuntu/ +jammy.*main' /etc/apt/sources.list /etc/apt/sources.list.d/*; then
                echo "deb-src http://archive.ubuntu.com/ubuntu/ jammy main" >> /etc/apt/sources.list
            fi
            if ! grep -E -q 'deb-src\s+http://archive\.ubuntu\.com/ubuntu/ +jammy.*universe' /etc/apt/sources.list /etc/apt/sources.list.d/*; then
                echo "deb-src http://archive.ubuntu.com/ubuntu/ jammy universe" >> /etc/apt/sources.list
            fi

            PACKAGES = "mkvtoolnix=70.0.0-0~ubuntu2204bunkus01 mkvtoolnix-gui=70.0.0-0~ubuntu2204bunkus01"
        else
            echo "**** MKVToolNix already installed. ****"
        fi
    fi

    echo "**** Installing packages ****"
    echo "\
    $PACKAGES \
    mediainfo \
    unzip" >> /mod-repo-packages-to-install.list
fi