name: Build Image

on: [push, pull_request_target, workflow_dispatch]

env:
  GITHUB_REPO: "linuxserver/docker-mods" #don't modify
  ENDPOINT: "linuxserver/mods" #don't modify
  BASEIMAGE: "universal" #replace
  MODNAME: "docker-in-docker" #replace

jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set Vars
        id: outputs
        run: |
          echo "GITHUB_REPO=${{ env.GITHUB_REPO }}" >> $GITHUB_OUTPUT
          echo "ENDPOINT=${{ env.ENDPOINT }}" >> $GITHUB_OUTPUT
          echo "BASEIMAGE=${{ env.BASEIMAGE }}" >> $GITHUB_OUTPUT
          echo "MODNAME=${{ env.MODNAME }}" >> $GITHUB_OUTPUT
          # **** If the mod needs to be versioned, set the versioning logic below. Otherwise leave as is. ****
          COMPOSE_RELEASE=$(curl -sX GET "https://api.github.com/repos/docker/compose/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||')
          DOCKER_RELEASE=$(curl -sX GET "https://api.github.com/repos/moby/moby/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||')
          MOD_VERSION="${DOCKER_RELEASE}-${COMPOSE_RELEASE}"
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_OUTPUT
    outputs:
      GITHUB_REPO: ${{ steps.outputs.outputs.GITHUB_REPO }}
      ENDPOINT: ${{ steps.outputs.outputs.ENDPOINT }}
      BASEIMAGE: ${{ steps.outputs.outputs.BASEIMAGE }}
      MODNAME: ${{ steps.outputs.outputs.MODNAME }}
      MOD_VERSION: ${{ steps.outputs.outputs.MOD_VERSION }}

  build:
    uses: linuxserver/github-workflows/.github/workflows/docker-mod-builder.yml@v1
    needs: set-vars
    secrets:
      CR_USER: ${{ secrets.CR_USER }}
      CR_PAT: ${{ secrets.CR_PAT }}
      DOCKERUSER: ${{ secrets.DOCKERUSER }}
      DOCKERPASS: ${{ secrets.DOCKERPASS }}
    with:
      GITHUB_REPO: ${{ needs.set-vars.outputs.GITHUB_REPO }}
      ENDPOINT: ${{ needs.set-vars.outputs.ENDPOINT }}
      BASEIMAGE: ${{ needs.set-vars.outputs.BASEIMAGE }}
      MODNAME: ${{ needs.set-vars.outputs.MODNAME }}
      MOD_VERSION: ${{ needs.set-vars.outputs.MOD_VERSION }}
